# site settings
title: Bach-Chor Hagen
#subtitle: Vokalensemble seit 1985
email: cantate@bach-chor-hagen.de
description: Herzlich Willkommen auf unserer Homepage
baseurl: # the subpath of your site, e.g. /blog
domain: smuecke.github.io
author: Sascha Mücke
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  Twitter:
  Facebook: https://www.facebook.com/BachChorHagen
  Slack: https://bachchorhagen.slack.com

# build settings
markdown: kramdown

sass:
  style: compressed

include: ['_pages']

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md 
